export const DYNAMIC_TABLE_ELEMENT = 'DYNAMIC_TABLE_ELEMENT';
export const DYNAMIC_TABLE_DESCRIPTOR = 'DYNAMIC_TABLE_DESCRIPTOR';
export const DEPENDENCY_RESOLVER = 'DEPENDENCY_RESOLVER';
export const DYNAMIC_FORM = 'DYNAMIC_FORM';
export const DYNAMIC_FORM_CALLBACK = 'DYNAMIC_FORM_CALLBACK';
export const DYNAMIC_FORM_MODEL = 'DYNAMIC_FORM_MODEL';
export const DYNAMIC_FORM_SYNC_BUS = 'DYNAMIC_FORM_SYNC_BUS';
